-- Requêtes Access extraites de LTA_ADM.accdb (table système MSysQueries, 174 lignes décodées)
-- Attributs : 5=FROM(table+alias) 6=SELECT 7=JOIN(Flag 1=INNER, 2=LEFT) 8=WHERE 9=GROUP BY 11=ORDER BY

-- ===== R_ABSENCE_ETUDIANT =====
SELECT
  I.ID_INSCRIPTION,
  E.MATRICULE,
  E.NOM,
  E.PRENOM,
  C.LIBELLE AS CLASSE,
  Sum(A.NB_HEURES) AS TOTAL_HEURES,
  Sum(IIf(A.JUSTIFIEE = True, A.NB_HEURES, 0)) AS HEURES_JUSTIFIEES
FROM
  ABSENCE AS A
  INNER JOIN INSCRIPTION AS I ON A.ID_INSCRIPTION = I.ID_INSCRIPTION
  INNER JOIN ETUDIANT AS E ON I.ID_ETUDIANT = E.ID_ETUDIANT
  INNER JOIN CLASSE AS C ON I.ID_CLASSE = C.ID_CLASSE
GROUP BY I.ID_INSCRIPTION, E.MATRICULE, E.NOM, E.PRENOM, C.LIBELLE;

-- ===== R_EDT_CLASSE =====
SELECT
  C.LIBELLE AS CLASSE,
  EDT.JOUR,
  CR.ORDRE_CRE,
  CR.HEURE_DEBUT,
  CR.HEURE_FIN,
  M.MATIERE,
  F.NOM & ' ' & F.PRENOM AS FORMATEUR,
  S.NOM_SALLE
FROM
  EMPLOI_DU_TEMPS AS EDT
  INNER JOIN CRENEAU AS CR ON EDT.ID_CRENEAU = CR.ID_CRENEAU
  INNER JOIN PROGRAMME AS P ON EDT.ID_PROG = P.ID_PROG
  INNER JOIN CLASSE AS C ON P.ID_CLASSE = C.ID_CLASSE
  INNER JOIN MATIERE AS M ON P.CODE_MATIERE = M.CODE_MATIERE
  LEFT JOIN FORMATEUR AS F ON P.ID_FORMATEUR = F.ID_FORMATEUR
  LEFT JOIN SALLE AS S ON EDT.ID_SALLE = S.ID_SALLE
WHERE EDT.ACTIF = True
ORDER BY C.LIBELLE, EDT.JOUR, CR.ORDRE_CRE;

-- ===== R_SITUATION_ECOLAGE =====
SELECT
  E.MATRICULE,
  E.NOM,
  E.PRENOM,
  C.LIBELLE AS CLASSE,
  I.ID_INSCRIPTION,
  Sum(ECH.MONTANT_DU - Nz(ECH.REMISE,0)) AS TOTAL_DU,
  Sum(Nz(PE.TOTAL_PAYE,0)) AS TOTAL_PAYE,
  Sum(ECH.MONTANT_DU - Nz(ECH.REMISE,0)) - Sum(Nz(PE.TOTAL_PAYE,0)) AS RESTE
FROM
  ECHEANCIER AS ECH
  LEFT JOIN R_PAIEMENT_ECHEANCE AS PE ON ECH.ID_ECHEANCE = PE.ID_ECHEANCE
  INNER JOIN INSCRIPTION AS I ON ECH.ID_INSCRIPTION = I.ID_INSCRIPTION
  INNER JOIN ETUDIANT AS E ON I.ID_ETUDIANT = E.ID_ETUDIANT
  INNER JOIN CLASSE AS C ON I.ID_CLASSE = C.ID_CLASSE
GROUP BY E.MATRICULE, E.NOM, E.PRENOM, C.LIBELLE, I.ID_INSCRIPTION;

-- ===== R_PAIEMENT_ECHEANCE =====
SELECT
  ID_ECHEANCE,
  Sum(MONTANT) AS TOTAL_PAYE,
  Max(DATE_PAIEMENT) AS DERNIER_PAIEMENT
FROM
  PAIEMENT
GROUP BY ID_ECHEANCE;

-- ===== R_BULLETIN_DETAIL =====
SELECT
  E.MATRICULE,
  E.NOM,
  E.PRENOM,
  C.LIBELLE AS CLASSE,
  PE.LIBELLE AS PERIODE,
  M.MATIERE,
  BL.MOYENNE_MAT,
  BL.COEFFICIENT,
  BL.POINTS,
  BL.RANG_MAT,
  B.MOYENNE,
  B.RANG,
  B.EFFECTIF,
  B.DECISION
FROM
  BULLETIN AS B
  INNER JOIN BULLETIN_LIGNE AS BL ON B.ID_BULLETIN = BL.ID_BULLETIN
  INNER JOIN MATIERE AS M ON BL.CODE_MATIERE = M.CODE_MATIERE
  INNER JOIN INSCRIPTION AS I ON B.ID_INSCRIPTION = I.ID_INSCRIPTION
  INNER JOIN ETUDIANT AS E ON I.ID_ETUDIANT = E.ID_ETUDIANT
  INNER JOIN CLASSE AS C ON I.ID_CLASSE = C.ID_CLASSE
  INNER JOIN PERIODE_EVAL AS PE ON B.ID_PERIODE = PE.ID_PERIODE
ORDER BY C.LIBELLE, E.NOM, M.MATIERE;

-- ===== R_MOYENNE_PERIODE =====
SELECT
  ID_INSCRIPTION,
  ID_PERIODE,
  ID_CLASSE,
  Sum(MOYENNE_MAT * COEFFICIENT) AS TOTAL_POINTS,
  Sum(COEFFICIENT) AS TOTAL_COEF,
  Sum(MOYENNE_MAT * COEFFICIENT) / Sum(COEFFICIENT) AS MOYENNE
FROM
  R_MOYENNE_MATIERE
GROUP BY ID_INSCRIPTION, ID_PERIODE, ID_CLASSE;

-- ===== R_MOYENNE_MATIERE =====
SELECT
  I.ID_INSCRIPTION,
  EV.ID_PERIODE,
  P.ID_CLASSE,
  P.CODE_MATIERE,
  P.COEFFICIENT,
  P.ID_FORMATEUR,
  Sum(N.VALEUR_NOTE / EV.BAREME * 20 * EV.POIDS) / Sum(EV.POIDS) AS MOYENNE_MAT
FROM
  NOTE AS N
  INNER JOIN EVALUATION AS EV ON N.ID_EVALUATION = EV.ID_EVALUATION
  INNER JOIN PROGRAMME AS P ON EV.ID_PROG = P.ID_PROG
  INNER JOIN INSCRIPTION AS I ON N.ID_INSCRIPTION = I.ID_INSCRIPTION
WHERE N.ABSENT = False AND N.VALEUR_NOTE Is Not Null
GROUP BY I.ID_INSCRIPTION, EV.ID_PERIODE, P.ID_CLASSE, P.CODE_MATIERE, P.COEFFICIENT, P.ID_FORMATEUR;

-- ===== R_LISTE_ETUDIANT =====
SELECT
  I.ID_INSCRIPTION,
  E.MATRICULE,
  E.NOM,
  E.PRENOM,
  E.SEXE,
  E.DATE_NAISSANCE,
  E.TEL,
  C.LIBELLE AS CLASSE,
  F.FILIERE,
  N.NIVEAU,
  A.LIBELLE AS ANNEE,
  I.STATUT
FROM
  INSCRIPTION AS I
  INNER JOIN ETUDIANT AS E ON I.ID_ETUDIANT = E.ID_ETUDIANT
  INNER JOIN CLASSE AS C ON I.ID_CLASSE = C.ID_CLASSE
  INNER JOIN FILIERE AS F ON C.CODE_FILIERE = F.CODE_FILIERE
  INNER JOIN NIVEAU AS N ON C.CODE_NIVEAU = N.CODE_NIVEAU
  INNER JOIN ANNEE_SCOLAIRE AS A ON C.ID_ANNEE = A.ID_ANNEE
ORDER BY C.LIBELLE, E.NOM, E.PRENOM;
